### PR TITLE
Use clear() in PriorityQueue constructor

### PR DESCRIPTION
**Pull request by dantudor**
Additionally also sets the capacity of the queue to the min_capacity.

### CODE REVIEW

**Comment by rtheunissen** [comment]
I'm not so sure if I like this even though it technically reduces duplication. `clear` implies that there may be values to remove, and might be better to be explicit with the way a constructor initializes properties. 

A better alternative would be to create a third, private method called `reset`, which both `clear` and the constructor would call.

**Comment by dantudor** [comment]
Hi Rudi,

Reset may be a better name, but it also implies that values are being removed and restored to the original state. The duplication of code is minor, but seeing the two methods next to each other performing the same task hurt my eyes. 

Outside of code duplication, the only issue was that the minimum capacity wasn't being set on construct.

If you'd prefer a private ```reset``` method which both ```clear``` and the constructor call I'll implement and update this PR.

**Comment by rtheunissen** [comment]
> If you'd prefer a private reset method which both clear and the constructor call I'll implement and update this PR

I like this. Also, wasn't the initial capacity set when defined anyway?

A private `reset` makes sense to me.

**Comment by rtheunissen** [comment]
Create a new PR I think :+1:

**Pull request closed without merging**
