### PR TITLE
Improved Trait inheritance to resolve scrutinizers undeclared propert…

### PR DESCRIPTION
**Pull request by dantudor**
…ies and methods

### CODE REVIEW

**Comment by rtheunissen** [comment]
`Sequence` shouldn't use `SquaredCapacity` by default, because it doesn't necessarily use a squared capacity (only Deque does). 

Best solution would be to not define the properties in the Trait, but explicitly define them in each class.

**Comment by dantudor** [comment]
Missed that.
Then I think the Traits will need to declare abstract methods for methods that that require the parent class to define.

**Comment by rtheunissen** [comment]
That has been the intention, eg. `abstract protected function increaseCapacity()`.

I'll take a look at exactly what Scrutinizer is complaining about.

**Comment by rtheunissen** [comment]
@dantudor Could you please check to see if this is still applicable? Feel free to close otherwise.

**Pull request closed without merging**
